//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 3.4
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// $ANTLR 3.4 ./LtlSharp/LTL.g 2012-07-11 11:28:35

// The variable 'variable' is assigned but its value is never used.
#pragma warning disable 219
// Unreachable code detected.
#pragma warning disable 162
// Missing XML comment for publicly visible type or member 'Type_or_Member'
#pragma warning disable 1591
// CLS compliance checking will not be performed on 'type' because it is not visible from outside this assembly.
#pragma warning disable 3019


using System.Collections.Generic;
using Antlr.Runtime;
using Antlr.Runtime.Misc;


using Antlr.Runtime.Tree;
using RewriteRuleITokenStream = Antlr.Runtime.Tree.RewriteRuleTokenStream;

namespace  LtlSharp 
{
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "3.4")]
[System.CLSCompliant(false)]
public partial class LTLParser : Antlr.Runtime.Parser
{
	internal static readonly string[] tokenNames = new string[] {
		"<invalid>", "<EOR>", "<DOWN>", "<UP>", "PROPOSITION", "'!'", "'&'", "'('", "')'", "'->'", "'F'", "'G'", "'R'", "'U'", "'W'", "'X'", "'|'"
	};
	public const int EOF=-1;
	public const int T__5=5;
	public const int T__6=6;
	public const int T__7=7;
	public const int T__8=8;
	public const int T__9=9;
	public const int T__10=10;
	public const int T__11=11;
	public const int T__12=12;
	public const int T__13=13;
	public const int T__14=14;
	public const int T__15=15;
	public const int T__16=16;
	public const int PROPOSITION=4;

	public LTLParser(ITokenStream input)
		: this(input, new RecognizerSharedState())
	{
	}
	public LTLParser(ITokenStream input, RecognizerSharedState state)
		: base(input, state)
	{
		ITreeAdaptor treeAdaptor = default(ITreeAdaptor);
		CreateTreeAdaptor(ref treeAdaptor);
		TreeAdaptor = treeAdaptor ?? new CommonTreeAdaptor();
		OnCreated();
	}
	// Implement this function in your helper file to use a custom tree adaptor
	partial void CreateTreeAdaptor(ref ITreeAdaptor adaptor);

	private ITreeAdaptor adaptor;

	public ITreeAdaptor TreeAdaptor
	{
		get
		{
			return adaptor;
		}

		set
		{
			this.adaptor = value;
		}
	}

	public override string[] TokenNames { get { return LTLParser.tokenNames; } }
	public override string GrammarFileName { get { return "./LtlSharp/LTL.g"; } }


	partial void OnCreated();
	partial void EnterRule(string ruleName, int ruleIndex);
	partial void LeaveRule(string ruleName, int ruleIndex);

	#region Rules
	public sealed partial class parse_return : AstParserRuleReturnScope<object, IToken>
	{
		public Expression value;
		public parse_return(LTLParser grammar) {OnCreated(grammar);}
		partial void OnCreated(LTLParser grammar);
	}

	partial void EnterRule_parse();
	partial void LeaveRule_parse();

	// $ANTLR start "parse"
	// ./LtlSharp/LTL.g:11:8: public parse returns [Expression value] : formula EOF ;
	[GrammarRule("parse")]
	public LTLParser.parse_return parse()
	{
		EnterRule_parse();
		EnterRule("parse", 1);
		TraceIn("parse", 1);
		LTLParser.parse_return retval = new LTLParser.parse_return(this);
		retval.Start = (IToken)input.LT(1);

		object root_0 = default(object);

		IToken EOF2 = default(IToken);
		LTLParser.formula_return formula1 = default(LTLParser.formula_return);

		object EOF2_tree = default(object);
		try { DebugEnterRule(GrammarFileName, "parse");
		DebugLocation(11, 2);
		try
		{
			// ./LtlSharp/LTL.g:12:3: ( formula EOF )
			DebugEnterAlt(1);
			// ./LtlSharp/LTL.g:12:6: formula EOF
			{
			root_0 = (object)adaptor.Nil();

			DebugLocation(12, 6);
			PushFollow(Follow._formula_in_parse59);
			formula1=formula();
			PopFollow();

			adaptor.AddChild(root_0, formula1.Tree);
			DebugLocation(12, 14);
			EOF2=(IToken)Match(input,EOF,Follow._EOF_in_parse61); 
			EOF2_tree = (object)adaptor.Create(EOF2);
			adaptor.AddChild(root_0, EOF2_tree);
			DebugLocation(12, 18);
			retval.value = (formula1!=null?formula1.value:default(Expression));

			}

			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("parse", 1);
			LeaveRule("parse", 1);
			LeaveRule_parse();
		}
		DebugLocation(13, 2);
		} finally { DebugExitRule(GrammarFileName, "parse"); }
		return retval;

	}
	// $ANTLR end "parse"

	private sealed partial class formula_return : AstParserRuleReturnScope<object, IToken>
	{
		public Expression value;
		public formula_return(LTLParser grammar) {OnCreated(grammar);}
		partial void OnCreated(LTLParser grammar);
	}

	partial void EnterRule_formula();
	partial void LeaveRule_formula();

	// $ANTLR start "formula"
	// ./LtlSharp/LTL.g:15:1: formula returns [Expression value] : f= binary ;
	[GrammarRule("formula")]
	private LTLParser.formula_return formula()
	{
		EnterRule_formula();
		EnterRule("formula", 2);
		TraceIn("formula", 2);
		LTLParser.formula_return retval = new LTLParser.formula_return(this);
		retval.Start = (IToken)input.LT(1);

		object root_0 = default(object);

		LTLParser.binary_return f = default(LTLParser.binary_return);

		try { DebugEnterRule(GrammarFileName, "formula");
		DebugLocation(15, 2);
		try
		{
			// ./LtlSharp/LTL.g:16:3: (f= binary )
			DebugEnterAlt(1);
			// ./LtlSharp/LTL.g:16:6: f= binary
			{
			root_0 = (object)adaptor.Nil();

			DebugLocation(16, 8);
			PushFollow(Follow._binary_in_formula87);
			f=binary();
			PopFollow();

			adaptor.AddChild(root_0, f.Tree);
			DebugLocation(16, 17);
			retval.value = (f!=null?f.value:default(Expression));

			}

			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("formula", 2);
			LeaveRule("formula", 2);
			LeaveRule_formula();
		}
		DebugLocation(17, 2);
		} finally { DebugExitRule(GrammarFileName, "formula"); }
		return retval;

	}
	// $ANTLR end "formula"

	private sealed partial class binary_return : AstParserRuleReturnScope<object, IToken>
	{
		public Expression value;
		public binary_return(LTLParser grammar) {OnCreated(grammar);}
		partial void OnCreated(LTLParser grammar);
	}

	partial void EnterRule_binary();
	partial void LeaveRule_binary();

	// $ANTLR start "binary"
	// ./LtlSharp/LTL.g:19:1: binary returns [Expression value] : a= implication ( 'U' b= binary | 'R' b= binary | 'W' b= binary )? ;
	[GrammarRule("binary")]
	private LTLParser.binary_return binary()
	{
		EnterRule_binary();
		EnterRule("binary", 3);
		TraceIn("binary", 3);
		LTLParser.binary_return retval = new LTLParser.binary_return(this);
		retval.Start = (IToken)input.LT(1);

		object root_0 = default(object);

		IToken char_literal3 = default(IToken);
		IToken char_literal4 = default(IToken);
		IToken char_literal5 = default(IToken);
		LTLParser.implication_return a = default(LTLParser.implication_return);
		LTLParser.binary_return b = default(LTLParser.binary_return);

		object char_literal3_tree = default(object);
		object char_literal4_tree = default(object);
		object char_literal5_tree = default(object);
		try { DebugEnterRule(GrammarFileName, "binary");
		DebugLocation(19, 2);
		try
		{
			// ./LtlSharp/LTL.g:20:3: (a= implication ( 'U' b= binary | 'R' b= binary | 'W' b= binary )? )
			DebugEnterAlt(1);
			// ./LtlSharp/LTL.g:20:6: a= implication ( 'U' b= binary | 'R' b= binary | 'W' b= binary )?
			{
			root_0 = (object)adaptor.Nil();

			DebugLocation(20, 8);
			PushFollow(Follow._implication_in_binary111);
			a=implication();
			PopFollow();

			adaptor.AddChild(root_0, a.Tree);
			DebugLocation(20, 22);
			 retval.value = (a!=null?a.value:default(Expression)); 
			DebugLocation(21, 6);
			// ./LtlSharp/LTL.g:21:6: ( 'U' b= binary | 'R' b= binary | 'W' b= binary )?
			int alt1=4;
			try { DebugEnterSubRule(1);
			try { DebugEnterDecision(1, false);
			switch (input.LA(1))
			{
			case 13:
				{
				alt1 = 1;
				}
				break;
			case 12:
				{
				alt1 = 2;
				}
				break;
			case 14:
				{
				alt1 = 3;
				}
				break;
			}

			} finally { DebugExitDecision(1); }
			switch (alt1)
			{
			case 1:
				DebugEnterAlt(1);
				// ./LtlSharp/LTL.g:21:8: 'U' b= binary
				{
				DebugLocation(21, 8);
				char_literal3=(IToken)Match(input,13,Follow._13_in_binary123); 
				char_literal3_tree = (object)adaptor.Create(char_literal3);
				adaptor.AddChild(root_0, char_literal3_tree);
				DebugLocation(21, 14);
				PushFollow(Follow._binary_in_binary129);
				b=binary();
				PopFollow();

				adaptor.AddChild(root_0, b.Tree);
				DebugLocation(21, 23);
				 retval.value = new Until ((a!=null?a.value:default(Expression)), (b!=null?b.value:default(Expression))); 

				}
				break;
			case 2:
				DebugEnterAlt(2);
				// ./LtlSharp/LTL.g:22:8: 'R' b= binary
				{
				DebugLocation(22, 8);
				char_literal4=(IToken)Match(input,12,Follow._12_in_binary140); 
				char_literal4_tree = (object)adaptor.Create(char_literal4);
				adaptor.AddChild(root_0, char_literal4_tree);
				DebugLocation(22, 14);
				PushFollow(Follow._binary_in_binary146);
				b=binary();
				PopFollow();

				adaptor.AddChild(root_0, b.Tree);
				DebugLocation(22, 23);
				 retval.value = new Release ((a!=null?a.value:default(Expression)), (b!=null?b.value:default(Expression))); 

				}
				break;
			case 3:
				DebugEnterAlt(3);
				// ./LtlSharp/LTL.g:23:8: 'W' b= binary
				{
				DebugLocation(23, 8);
				char_literal5=(IToken)Match(input,14,Follow._14_in_binary157); 
				char_literal5_tree = (object)adaptor.Create(char_literal5);
				adaptor.AddChild(root_0, char_literal5_tree);
				DebugLocation(23, 14);
				PushFollow(Follow._binary_in_binary163);
				b=binary();
				PopFollow();

				adaptor.AddChild(root_0, b.Tree);
				DebugLocation(23, 23);
				 retval.value = new Unless ((a!=null?a.value:default(Expression)), (b!=null?b.value:default(Expression))); 

				}
				break;

			}
			} finally { DebugExitSubRule(1); }


			}

			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("binary", 3);
			LeaveRule("binary", 3);
			LeaveRule_binary();
		}
		DebugLocation(25, 2);
		} finally { DebugExitRule(GrammarFileName, "binary"); }
		return retval;

	}
	// $ANTLR end "binary"

	private sealed partial class implication_return : AstParserRuleReturnScope<object, IToken>
	{
		public Expression value;
		public implication_return(LTLParser grammar) {OnCreated(grammar);}
		partial void OnCreated(LTLParser grammar);
	}

	partial void EnterRule_implication();
	partial void LeaveRule_implication();

	// $ANTLR start "implication"
	// ./LtlSharp/LTL.g:27:1: implication returns [Expression value] : a= conjunction ( '->' b= implication )? ;
	[GrammarRule("implication")]
	private LTLParser.implication_return implication()
	{
		EnterRule_implication();
		EnterRule("implication", 4);
		TraceIn("implication", 4);
		LTLParser.implication_return retval = new LTLParser.implication_return(this);
		retval.Start = (IToken)input.LT(1);

		object root_0 = default(object);

		IToken string_literal6 = default(IToken);
		LTLParser.conjunction_return a = default(LTLParser.conjunction_return);
		LTLParser.implication_return b = default(LTLParser.implication_return);

		object string_literal6_tree = default(object);
		try { DebugEnterRule(GrammarFileName, "implication");
		DebugLocation(27, 2);
		try
		{
			// ./LtlSharp/LTL.g:28:3: (a= conjunction ( '->' b= implication )? )
			DebugEnterAlt(1);
			// ./LtlSharp/LTL.g:28:6: a= conjunction ( '->' b= implication )?
			{
			root_0 = (object)adaptor.Nil();

			DebugLocation(28, 8);
			PushFollow(Follow._conjunction_in_implication195);
			a=conjunction();
			PopFollow();

			adaptor.AddChild(root_0, a.Tree);
			DebugLocation(28, 22);
			 retval.value = (a!=null?a.value:default(Expression)); 
			DebugLocation(28, 45);
			// ./LtlSharp/LTL.g:28:45: ( '->' b= implication )?
			int alt2=2;
			try { DebugEnterSubRule(2);
			try { DebugEnterDecision(2, false);
			int LA2_0 = input.LA(1);

			if ((LA2_0==9))
			{
				alt2 = 1;
			}
			} finally { DebugExitDecision(2); }
			switch (alt2)
			{
			case 1:
				DebugEnterAlt(1);
				// ./LtlSharp/LTL.g:28:46: '->' b= implication
				{
				DebugLocation(28, 46);
				string_literal6=(IToken)Match(input,9,Follow._9_in_implication200); 
				string_literal6_tree = (object)adaptor.Create(string_literal6);
				adaptor.AddChild(root_0, string_literal6_tree);
				DebugLocation(28, 53);
				PushFollow(Follow._implication_in_implication206);
				b=implication();
				PopFollow();

				adaptor.AddChild(root_0, b.Tree);
				DebugLocation(28, 67);
				 retval.value = new Implication ((a!=null?a.value:default(Expression)), (b!=null?b.value:default(Expression))); 

				}
				break;

			}
			} finally { DebugExitSubRule(2); }


			}

			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("implication", 4);
			LeaveRule("implication", 4);
			LeaveRule_implication();
		}
		DebugLocation(29, 2);
		} finally { DebugExitRule(GrammarFileName, "implication"); }
		return retval;

	}
	// $ANTLR end "implication"

	private sealed partial class conjunction_return : AstParserRuleReturnScope<object, IToken>
	{
		public Expression value;
		public conjunction_return(LTLParser grammar) {OnCreated(grammar);}
		partial void OnCreated(LTLParser grammar);
	}

	partial void EnterRule_conjunction();
	partial void LeaveRule_conjunction();

	// $ANTLR start "conjunction"
	// ./LtlSharp/LTL.g:31:1: conjunction returns [Expression value] : a= disjunction ( '&' b= conjunction )? ;
	[GrammarRule("conjunction")]
	private LTLParser.conjunction_return conjunction()
	{
		EnterRule_conjunction();
		EnterRule("conjunction", 5);
		TraceIn("conjunction", 5);
		LTLParser.conjunction_return retval = new LTLParser.conjunction_return(this);
		retval.Start = (IToken)input.LT(1);

		object root_0 = default(object);

		IToken char_literal7 = default(IToken);
		LTLParser.disjunction_return a = default(LTLParser.disjunction_return);
		LTLParser.conjunction_return b = default(LTLParser.conjunction_return);

		object char_literal7_tree = default(object);
		try { DebugEnterRule(GrammarFileName, "conjunction");
		DebugLocation(31, 2);
		try
		{
			// ./LtlSharp/LTL.g:32:3: (a= disjunction ( '&' b= conjunction )? )
			DebugEnterAlt(1);
			// ./LtlSharp/LTL.g:32:6: a= disjunction ( '&' b= conjunction )?
			{
			root_0 = (object)adaptor.Nil();

			DebugLocation(32, 8);
			PushFollow(Follow._disjunction_in_conjunction234);
			a=disjunction();
			PopFollow();

			adaptor.AddChild(root_0, a.Tree);
			DebugLocation(32, 22);
			 retval.value = (a!=null?a.value:default(Expression)); 
			DebugLocation(32, 45);
			// ./LtlSharp/LTL.g:32:45: ( '&' b= conjunction )?
			int alt3=2;
			try { DebugEnterSubRule(3);
			try { DebugEnterDecision(3, false);
			int LA3_0 = input.LA(1);

			if ((LA3_0==6))
			{
				alt3 = 1;
			}
			} finally { DebugExitDecision(3); }
			switch (alt3)
			{
			case 1:
				DebugEnterAlt(1);
				// ./LtlSharp/LTL.g:32:46: '&' b= conjunction
				{
				DebugLocation(32, 46);
				char_literal7=(IToken)Match(input,6,Follow._6_in_conjunction239); 
				char_literal7_tree = (object)adaptor.Create(char_literal7);
				adaptor.AddChild(root_0, char_literal7_tree);
				DebugLocation(32, 52);
				PushFollow(Follow._conjunction_in_conjunction245);
				b=conjunction();
				PopFollow();

				adaptor.AddChild(root_0, b.Tree);
				DebugLocation(32, 66);
				 if (retval.value.GetType() == typeof(Conjunction)) { ((Conjunction) retval.value).Push ((b!=null?b.value:default(Expression))); } else { retval.value = new Conjunction (retval.value, (b!=null?b.value:default(Expression))); } 

				}
				break;

			}
			} finally { DebugExitSubRule(3); }


			}

			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("conjunction", 5);
			LeaveRule("conjunction", 5);
			LeaveRule_conjunction();
		}
		DebugLocation(33, 2);
		} finally { DebugExitRule(GrammarFileName, "conjunction"); }
		return retval;

	}
	// $ANTLR end "conjunction"

	private sealed partial class disjunction_return : AstParserRuleReturnScope<object, IToken>
	{
		public Expression value;
		public disjunction_return(LTLParser grammar) {OnCreated(grammar);}
		partial void OnCreated(LTLParser grammar);
	}

	partial void EnterRule_disjunction();
	partial void LeaveRule_disjunction();

	// $ANTLR start "disjunction"
	// ./LtlSharp/LTL.g:35:1: disjunction returns [Expression value] : a= unary ( '|' b= disjunction )? ;
	[GrammarRule("disjunction")]
	private LTLParser.disjunction_return disjunction()
	{
		EnterRule_disjunction();
		EnterRule("disjunction", 6);
		TraceIn("disjunction", 6);
		LTLParser.disjunction_return retval = new LTLParser.disjunction_return(this);
		retval.Start = (IToken)input.LT(1);

		object root_0 = default(object);

		IToken char_literal8 = default(IToken);
		LTLParser.unary_return a = default(LTLParser.unary_return);
		LTLParser.disjunction_return b = default(LTLParser.disjunction_return);

		object char_literal8_tree = default(object);
		try { DebugEnterRule(GrammarFileName, "disjunction");
		DebugLocation(35, 2);
		try
		{
			// ./LtlSharp/LTL.g:36:3: (a= unary ( '|' b= disjunction )? )
			DebugEnterAlt(1);
			// ./LtlSharp/LTL.g:36:6: a= unary ( '|' b= disjunction )?
			{
			root_0 = (object)adaptor.Nil();

			DebugLocation(36, 8);
			PushFollow(Follow._unary_in_disjunction273);
			a=unary();
			PopFollow();

			adaptor.AddChild(root_0, a.Tree);
			DebugLocation(36, 16);
			 retval.value = (a!=null?a.value:default(Expression)); 
			DebugLocation(36, 39);
			// ./LtlSharp/LTL.g:36:39: ( '|' b= disjunction )?
			int alt4=2;
			try { DebugEnterSubRule(4);
			try { DebugEnterDecision(4, false);
			int LA4_0 = input.LA(1);

			if ((LA4_0==16))
			{
				alt4 = 1;
			}
			} finally { DebugExitDecision(4); }
			switch (alt4)
			{
			case 1:
				DebugEnterAlt(1);
				// ./LtlSharp/LTL.g:36:40: '|' b= disjunction
				{
				DebugLocation(36, 40);
				char_literal8=(IToken)Match(input,16,Follow._16_in_disjunction278); 
				char_literal8_tree = (object)adaptor.Create(char_literal8);
				adaptor.AddChild(root_0, char_literal8_tree);
				DebugLocation(36, 46);
				PushFollow(Follow._disjunction_in_disjunction284);
				b=disjunction();
				PopFollow();

				adaptor.AddChild(root_0, b.Tree);
				DebugLocation(36, 60);
				 if (retval.value.GetType() == typeof(Disjunction)) { ((Disjunction) retval.value).Push ((b!=null?b.value:default(Expression))); } else { retval.value = new Disjunction (retval.value, (b!=null?b.value:default(Expression))); } 

				}
				break;

			}
			} finally { DebugExitSubRule(4); }


			}

			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("disjunction", 6);
			LeaveRule("disjunction", 6);
			LeaveRule_disjunction();
		}
		DebugLocation(37, 2);
		} finally { DebugExitRule(GrammarFileName, "disjunction"); }
		return retval;

	}
	// $ANTLR end "disjunction"

	private sealed partial class unary_return : AstParserRuleReturnScope<object, IToken>
	{
		public Expression value;
		public unary_return(LTLParser grammar) {OnCreated(grammar);}
		partial void OnCreated(LTLParser grammar);
	}

	partial void EnterRule_unary();
	partial void LeaveRule_unary();

	// $ANTLR start "unary"
	// ./LtlSharp/LTL.g:39:1: unary returns [Expression value] : ( atom | '!' a= unary | 'X' a= unary | 'F' a= unary | 'G' a= unary );
	[GrammarRule("unary")]
	private LTLParser.unary_return unary()
	{
		EnterRule_unary();
		EnterRule("unary", 7);
		TraceIn("unary", 7);
		LTLParser.unary_return retval = new LTLParser.unary_return(this);
		retval.Start = (IToken)input.LT(1);

		object root_0 = default(object);

		IToken char_literal10 = default(IToken);
		IToken char_literal11 = default(IToken);
		IToken char_literal12 = default(IToken);
		IToken char_literal13 = default(IToken);
		LTLParser.unary_return a = default(LTLParser.unary_return);
		LTLParser.atom_return atom9 = default(LTLParser.atom_return);

		object char_literal10_tree = default(object);
		object char_literal11_tree = default(object);
		object char_literal12_tree = default(object);
		object char_literal13_tree = default(object);
		try { DebugEnterRule(GrammarFileName, "unary");
		DebugLocation(39, 2);
		try
		{
			// ./LtlSharp/LTL.g:40:3: ( atom | '!' a= unary | 'X' a= unary | 'F' a= unary | 'G' a= unary )
			int alt5=5;
			try { DebugEnterDecision(5, false);
			switch (input.LA(1))
			{
			case PROPOSITION:
			case 7:
				{
				alt5 = 1;
				}
				break;
			case 5:
				{
				alt5 = 2;
				}
				break;
			case 15:
				{
				alt5 = 3;
				}
				break;
			case 10:
				{
				alt5 = 4;
				}
				break;
			case 11:
				{
				alt5 = 5;
				}
				break;
			default:
				{
					NoViableAltException nvae = new NoViableAltException("", 5, 0, input);
					DebugRecognitionException(nvae);
					throw nvae;
				}
			}

			} finally { DebugExitDecision(5); }
			switch (alt5)
			{
			case 1:
				DebugEnterAlt(1);
				// ./LtlSharp/LTL.g:40:6: atom
				{
				root_0 = (object)adaptor.Nil();

				DebugLocation(40, 6);
				PushFollow(Follow._atom_in_unary306);
				atom9=atom();
				PopFollow();

				adaptor.AddChild(root_0, atom9.Tree);
				DebugLocation(40, 11);
				 retval.value = (atom9!=null?atom9.value:default(Expression)); 

				}
				break;
			case 2:
				DebugEnterAlt(2);
				// ./LtlSharp/LTL.g:41:5: '!' a= unary
				{
				root_0 = (object)adaptor.Nil();

				DebugLocation(41, 5);
				char_literal10=(IToken)Match(input,5,Follow._5_in_unary314); 
				char_literal10_tree = (object)adaptor.Create(char_literal10);
				adaptor.AddChild(root_0, char_literal10_tree);
				DebugLocation(41, 11);
				PushFollow(Follow._unary_in_unary320);
				a=unary();
				PopFollow();

				adaptor.AddChild(root_0, a.Tree);
				DebugLocation(41, 19);
				 retval.value = new Negation ((a!=null?a.value:default(Expression))); 

				}
				break;
			case 3:
				DebugEnterAlt(3);
				// ./LtlSharp/LTL.g:42:5: 'X' a= unary
				{
				root_0 = (object)adaptor.Nil();

				DebugLocation(42, 5);
				char_literal11=(IToken)Match(input,15,Follow._15_in_unary328); 
				char_literal11_tree = (object)adaptor.Create(char_literal11);
				adaptor.AddChild(root_0, char_literal11_tree);
				DebugLocation(42, 11);
				PushFollow(Follow._unary_in_unary334);
				a=unary();
				PopFollow();

				adaptor.AddChild(root_0, a.Tree);
				DebugLocation(42, 19);
				 retval.value = new Next ((a!=null?a.value:default(Expression))); 

				}
				break;
			case 4:
				DebugEnterAlt(4);
				// ./LtlSharp/LTL.g:43:5: 'F' a= unary
				{
				root_0 = (object)adaptor.Nil();

				DebugLocation(43, 5);
				char_literal12=(IToken)Match(input,10,Follow._10_in_unary342); 
				char_literal12_tree = (object)adaptor.Create(char_literal12);
				adaptor.AddChild(root_0, char_literal12_tree);
				DebugLocation(43, 11);
				PushFollow(Follow._unary_in_unary348);
				a=unary();
				PopFollow();

				adaptor.AddChild(root_0, a.Tree);
				DebugLocation(43, 19);
				 retval.value = new Finally ((a!=null?a.value:default(Expression))); 

				}
				break;
			case 5:
				DebugEnterAlt(5);
				// ./LtlSharp/LTL.g:44:5: 'G' a= unary
				{
				root_0 = (object)adaptor.Nil();

				DebugLocation(44, 5);
				char_literal13=(IToken)Match(input,11,Follow._11_in_unary356); 
				char_literal13_tree = (object)adaptor.Create(char_literal13);
				adaptor.AddChild(root_0, char_literal13_tree);
				DebugLocation(44, 11);
				PushFollow(Follow._unary_in_unary362);
				a=unary();
				PopFollow();

				adaptor.AddChild(root_0, a.Tree);
				DebugLocation(44, 19);
				 retval.value = new Globally ((a!=null?a.value:default(Expression))); 

				}
				break;

			}
			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("unary", 7);
			LeaveRule("unary", 7);
			LeaveRule_unary();
		}
		DebugLocation(45, 2);
		} finally { DebugExitRule(GrammarFileName, "unary"); }
		return retval;

	}
	// $ANTLR end "unary"

	private sealed partial class atom_return : AstParserRuleReturnScope<object, IToken>
	{
		public Expression value;
		public atom_return(LTLParser grammar) {OnCreated(grammar);}
		partial void OnCreated(LTLParser grammar);
	}

	partial void EnterRule_atom();
	partial void LeaveRule_atom();

	// $ANTLR start "atom"
	// ./LtlSharp/LTL.g:47:1: atom returns [Expression value] : ( PROPOSITION | '(' formula ')' );
	[GrammarRule("atom")]
	private LTLParser.atom_return atom()
	{
		EnterRule_atom();
		EnterRule("atom", 8);
		TraceIn("atom", 8);
		LTLParser.atom_return retval = new LTLParser.atom_return(this);
		retval.Start = (IToken)input.LT(1);

		object root_0 = default(object);

		IToken PROPOSITION14 = default(IToken);
		IToken char_literal15 = default(IToken);
		IToken char_literal17 = default(IToken);
		LTLParser.formula_return formula16 = default(LTLParser.formula_return);

		object PROPOSITION14_tree = default(object);
		object char_literal15_tree = default(object);
		object char_literal17_tree = default(object);
		try { DebugEnterRule(GrammarFileName, "atom");
		DebugLocation(47, 2);
		try
		{
			// ./LtlSharp/LTL.g:48:3: ( PROPOSITION | '(' formula ')' )
			int alt6=2;
			try { DebugEnterDecision(6, false);
			int LA6_0 = input.LA(1);

			if ((LA6_0==PROPOSITION))
			{
				alt6 = 1;
			}
			else if ((LA6_0==7))
			{
				alt6 = 2;
			}
			else
			{
				NoViableAltException nvae = new NoViableAltException("", 6, 0, input);
				DebugRecognitionException(nvae);
				throw nvae;
			}
			} finally { DebugExitDecision(6); }
			switch (alt6)
			{
			case 1:
				DebugEnterAlt(1);
				// ./LtlSharp/LTL.g:48:6: PROPOSITION
				{
				root_0 = (object)adaptor.Nil();

				DebugLocation(48, 6);
				PROPOSITION14=(IToken)Match(input,PROPOSITION,Follow._PROPOSITION_in_atom382); 
				PROPOSITION14_tree = (object)adaptor.Create(PROPOSITION14);
				adaptor.AddChild(root_0, PROPOSITION14_tree);
				DebugLocation(48, 18);
				 retval.value = new Proposition (PROPOSITION14.Text); 

				}
				break;
			case 2:
				DebugEnterAlt(2);
				// ./LtlSharp/LTL.g:49:5: '(' formula ')'
				{
				root_0 = (object)adaptor.Nil();

				DebugLocation(49, 5);
				char_literal15=(IToken)Match(input,7,Follow._7_in_atom390); 
				char_literal15_tree = (object)adaptor.Create(char_literal15);
				adaptor.AddChild(root_0, char_literal15_tree);
				DebugLocation(49, 9);
				PushFollow(Follow._formula_in_atom392);
				formula16=formula();
				PopFollow();

				adaptor.AddChild(root_0, formula16.Tree);
				DebugLocation(49, 17);
				char_literal17=(IToken)Match(input,8,Follow._8_in_atom394); 
				char_literal17_tree = (object)adaptor.Create(char_literal17);
				adaptor.AddChild(root_0, char_literal17_tree);
				DebugLocation(49, 21);
				 retval.value = new ParenthesedExpression ((formula16!=null?formula16.value:default(Expression))); 

				}
				break;

			}
			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("atom", 8);
			LeaveRule("atom", 8);
			LeaveRule_atom();
		}
		DebugLocation(50, 2);
		} finally { DebugExitRule(GrammarFileName, "atom"); }
		return retval;

	}
	// $ANTLR end "atom"
	#endregion Rules


	#region Follow sets
	private static class Follow
	{
		public static readonly BitSet _formula_in_parse59 = new BitSet(new ulong[]{0x0UL});
		public static readonly BitSet _EOF_in_parse61 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _binary_in_formula87 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _implication_in_binary111 = new BitSet(new ulong[]{0x7002UL});
		public static readonly BitSet _13_in_binary123 = new BitSet(new ulong[]{0x8CB0UL});
		public static readonly BitSet _binary_in_binary129 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _12_in_binary140 = new BitSet(new ulong[]{0x8CB0UL});
		public static readonly BitSet _binary_in_binary146 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _14_in_binary157 = new BitSet(new ulong[]{0x8CB0UL});
		public static readonly BitSet _binary_in_binary163 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _conjunction_in_implication195 = new BitSet(new ulong[]{0x202UL});
		public static readonly BitSet _9_in_implication200 = new BitSet(new ulong[]{0x8CB0UL});
		public static readonly BitSet _implication_in_implication206 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _disjunction_in_conjunction234 = new BitSet(new ulong[]{0x42UL});
		public static readonly BitSet _6_in_conjunction239 = new BitSet(new ulong[]{0x8CB0UL});
		public static readonly BitSet _conjunction_in_conjunction245 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _unary_in_disjunction273 = new BitSet(new ulong[]{0x10002UL});
		public static readonly BitSet _16_in_disjunction278 = new BitSet(new ulong[]{0x8CB0UL});
		public static readonly BitSet _disjunction_in_disjunction284 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _atom_in_unary306 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _5_in_unary314 = new BitSet(new ulong[]{0x8CB0UL});
		public static readonly BitSet _unary_in_unary320 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _15_in_unary328 = new BitSet(new ulong[]{0x8CB0UL});
		public static readonly BitSet _unary_in_unary334 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _10_in_unary342 = new BitSet(new ulong[]{0x8CB0UL});
		public static readonly BitSet _unary_in_unary348 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _11_in_unary356 = new BitSet(new ulong[]{0x8CB0UL});
		public static readonly BitSet _unary_in_unary362 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _PROPOSITION_in_atom382 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _7_in_atom390 = new BitSet(new ulong[]{0x8CB0UL});
		public static readonly BitSet _formula_in_atom392 = new BitSet(new ulong[]{0x100UL});
		public static readonly BitSet _8_in_atom394 = new BitSet(new ulong[]{0x2UL});
	}
	#endregion Follow sets
}

} // namespace  LtlSharp 
